"""
routes/auth.py

Role: Public authentication endpoints (NO admin required)
- Clerk webhook integration for user creation
- User login/check endpoint
- Returns user with role for frontend routing
- Uses numeric auto-increment user_id from database
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from db import get_db
from models import User, UserRole
from pydantic import BaseModel, EmailStr

router = APIRouter(
    prefix="/auth",
    tags=["Auth"]
)


class UserCreateRequest(BaseModel):
    """Request body for user creation from Clerk webhook"""
    email: EmailStr
    full_name: str


class UserLoginRequest(BaseModel):
    """Request body for user login"""
    email: EmailStr


@router.post("/create")
def auth_create_user(request: UserCreateRequest, db: Session = Depends(get_db)):
    """
    Create user from Clerk webhook.
    - If user already exists by email, return existing user
    - If not exists, create as MEMBER (default) with auto-increment user_id
    - Return user with role for frontend routing
    """
    # Check if user already exists by email (email is unique)
    existing_user = db.query(User).filter_by(email=request.email).first()
    if existing_user:
        return {
            "user_id": existing_user.user_id,
            "email": existing_user.email,
            "full_name": existing_user.full_name,
            "role": existing_user.role.value,
            "created_at": existing_user.created_at.isoformat() if existing_user.created_at else None
        }
    
    # Create new user as MEMBER (default role)
    # user_id will be auto-generated by database
    try:
        new_user = User(
            email=request.email,
            full_name=request.full_name,
            role=UserRole.MEMBER  # Default role
        )
        db.add(new_user)
        db.commit()
        db.refresh(new_user)
        
        return {
            "user_id": new_user.user_id,
            "email": new_user.email,
            "full_name": new_user.full_name,
            "role": new_user.role.value,
            "created_at": new_user.created_at.isoformat() if new_user.created_at else None
        }
    except Exception as e:
        db.rollback()
        if "Duplicate entry" in str(e) and "email" in str(e):
            raise HTTPException(status_code=400, detail="Email already exists")
        raise HTTPException(status_code=400, detail=f"Error creating user: {str(e)}")


@router.post("/login")
def auth_login_user(request: UserLoginRequest, db: Session = Depends(get_db)):
    """
    Login user by email - check if exists and return role for routing.
    Used when user is already authenticated with Clerk.
    """
    user = db.query(User).filter_by(email=request.email).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="User not found. Please create account first.")
    
    return {
        "user_id": user.user_id,
        "email": user.email,
        "full_name": user.full_name,
        "role": user.role.value,
        "created_at": user.created_at.isoformat() if user.created_at else None
    }


@router.get("/user/{user_id}")
def auth_get_user(user_id: int, db: Session = Depends(get_db)):
    """
    Get user details by numeric user_id
    """
    user = db.query(User).filter_by(user_id=user_id).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    return {
        "user_id": user.user_id,
        "email": user.email,
        "full_name": user.full_name,
        "role": user.role.value,
        "created_at": user.created_at.isoformat() if user.created_at else None
    }


@router.get("/user-by-email/{email}")
def auth_get_user_by_email(email: str, db: Session = Depends(get_db)):
    """
    Get user details by email (for Clerk integration)
    """
    user = db.query(User).filter_by(email=email).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    return {
        "user_id": user.user_id,
        "email": user.email,
        "full_name": user.full_name,
        "role": user.role.value,
        "created_at": user.created_at.isoformat() if user.created_at else None
    }
